### ISSUE TITLE
Priorità 3 - Usare i nostri loghi nel footer?

### ISSUE THREAD

**Issue by AlessioCeS** [lab121/covid19alessandria.help#10]

**Comment by Unm1821** [comment]
Non ne sono così sicuro. la pagina Chi siamo ha già grande importanza.
Oppure possiamo linkare la pagina Chi Siamo sulla scritta Make with love for Alessandria nel footer.
non saprei

**Comment by AlessioCeS** [comment]
Massi

**Comment by Unm1821** [comment]
ti sei offeso perché ho messo priorità 3? :))

**Comment by AlessioCeS** [comment]
Mannò
Sto cercando di far partire alessandriacomestai.org <http://alessandriacomestai.org/> e di non incasinare la promozione di quello con quella di covid19, Sciocco
A

**Comment by Unm1821** [comment]
io manderò il comunicato stampa domani, se riusciamo a fare il video insieme aspetto le 14 per mandarlo. il sito comunque lo pubblichiamo già stasera o domani mattina.

**Comment by AlessioCeS** [comment]
Se mi dite che facciamo il video, io ci sono.
A

**Comment by Unm1821** [comment]
maledetto whatsapp, i testi scompaiono in un attimo
