### ISSUE TITLE
Priorità 1 - "Plugin" per condivisione social? Della home ma anche delle singole segnalazioni?

### ISSUE THREAD

**Issue by AlessioCeS** [lab121/covid19alessandria.help#13]

**Comment by Unm1821** [comment]
Lo metterei nella barra in alto all'estrema destra

Sulla barra alla fine potrebbero risultare
a sx: hamburger / covid19alessandria.help
a dx: faq / privacy / condivisione sui social

**Comment by AlessioCeS** [comment]
Massi

**Comment by lussoluca** [comment]
aggiunto con share this
