### ISSUE TITLE
Inserire menu (anche solo panino) anche su versione desktop

### ISSUE THREAD

**Issue by AlessioCeS** [lab121/covid19alessandria.help#17]

**Comment by lussoluca** [comment]
nel senso mettiamo il burger anche in desktop con tutte le voci come mobile?

**Comment by AlessioCeS** [comment]
Se sei da desktop in una pagina, per andare altrove devi passare dal breadcumb (o come cazzo si chiama) o dalla home. Secondo me è scomodo

A

**Comment by lussoluca** [comment]
ho capito, quindi anche su desktop mettiamo lo stesso burger del mobile con dentro tutte le voci

**Comment by lussoluca** [comment]
in realtà su desktop il burger non è il massimo perché si apre a tutta pagina, ho messo le voci per esteso
