### ISSUE TITLE
Priorita 1 - Partner Istituzionali

### ISSUE THREAD

**Issue by Unm1821** [lab121/covid19alessandria.help#20]
nell'area loghi in home page, dobbiamo creare una categoria "**Partner Istituzionali**" (prima dall'alto, sopra i media) dove inserire i loghi di ospedale e comune. 
l'ospedale ha appena confermato il patrocinio, il comune ufficiosamente ma a giorni avremo anche il loro logo. potrebbe arrivare quello di asl ma non sono sicuro.

**Comment by Unm1821** [comment]
aggiungo I LOGHI man mano che arrivano su drive la cartella Partner istituzionali https://drive.google.com/drive/folders/1272KNhuS_g87jbudDRyjr8SnHbKFHr_B?usp=sharing

**Comment by lussoluca** [comment]
fatto
