### ISSUE TITLE
pagine elenco proposta modifiche minime layout

### ISSUE THREAD

**Issue by alescotti73** [lab121/covid19alessandria.help#24]
per pagine tipo https://covid19alessandria.help/scopri/mangiare-e-fare-la-spesa/consegne-alimentari/

- Ordinare AZ, oggi mi sa che è ordinata dall’ultima inserita, ordinando AZ sarebbe più intuitivo
- Telefono e mail potrebbero aprire direttamente whatsapp e client di posta al click/tap
- Come contatto non si può mettere anche FB? Click/tap > FB > messenger
- Su desktop l’elenco si vede con più voci su una riga, una sola voce per riga è più semplice da scorrere; in effetti su mobile è una voce per riga per ovvi motivi di spazio. Ma forse con ordinamento AZ sarebbe più semplice di adesso

**Comment by lussoluca** [comment]
> Ordinare AZ, oggi mi sa che è ordinata dall’ultima inserita, ordinando AZ sarebbe più intuitivo
Credo che l'ordinamento sia stato fatto ad hoc (@Unm1821 @dicarl )

> Telefono e mail potrebbero aprire direttamente whatsapp e client di posta al click/tap
ok

> Come contatto non si può mettere anche FB? Click/tap > FB > messenger
Oltre all'email e al telefono?

**Comment by alescotti73** [comment]
Si oltre mail e Tel, ma vedete voi se vi sembrano sensate e fattibili eh! Facebook mi pare link utile ma magari è una fissa mia

**Comment by Unm1821** [comment]
Questi aggiornamenti si rendono sempre meno utili man mano che riapriranno le attività.
