### ISSUE TITLE
home modifiche minime

### ISSUE THREAD

**Issue by alescotti73** [lab121/covid19alessandria.help#25]
- Sotto “Segnala” una frase di spiegazione, tipo “compila e la redazione valuterà e nel caso pubblicherà” oppure “Come funziona? Leggi le fAQ”

- Categoria: ordinare AZ

- Privacy: link in nuova tab alla pagina

**Comment by lussoluca** [comment]
> Sotto “Segnala” una frase di spiegazione, tipo “compila e la redazione valuterà e nel caso pubblicherà” oppure “Come funziona? Leggi le fAQ”

Ok (@Unm1821 che frase mettiamo?)

> Categoria: ordinare AZ

Intendi le voci nella tendina? Ok per me

> Privacy: link in nuova tab alla pagina

Ok

**Comment by alescotti73** [comment]
@Unm1821 che frase? "compila  il modulo per richiedere una pubblicazione. Per dettagli leggi le faq” 
Che ne dite?

**Comment by Unm1821** [comment]
pagina HOME (sotto Segnala): Compila il form per segnalarci una nuova informazione o un'aggiornamento importante. Ti risponderemo appena possibile confermandoti la pubblicazione della notizia o la segnalazione alle autorità competenti.
pagina PARTECIPA: togliere la voce Segnala. (la frase di spiegazione è già nella riga sopra)
pagina EMERGENZE (sotto Segnala un'emergenza): Compila il form per segnalarci un'emergenza o una situazione di bisogno. Se necessario, segnaleremo l'informazione alle autorità competenti e/o ti risponderemo per offrirti una possibile soluzione.


ps: scusate il ritado
