### ISSUE TITLE
Priorità 1 - evidenziare ultimi caricamenti (non ho idea come)

### ISSUE THREAD

**Issue by Unm1821** [lab121/covid19alessandria.help#27]
e forse non dovrebbe valere per gli esercizi commerciali, intendo che una news è importante sulle informazioni utili, sui servizi alla persona, sui contributi economici, sulle iniziative solidali ma NON credo lo sia per la categoria mangiare e bere

**Comment by lussoluca** [comment]
fatto

**Comment by jjciava** [comment]
Inserire la sezione emergenze tra gli ultimi caricamenti in Home page

**Comment by lussoluca** [comment]
fatto

**Comment by lussoluca** [comment]
fatto
