### ISSUE TITLE
Priorità 1 - nuova categoria PARTNER in loghi home page e inserimento logo CSVAA

### ISSUE THREAD

**Issue by Unm1821** [lab121/covid19alessandria.help#28]
![csvaa](https://user-images.githubusercontent.com/62957867/79220366-25844700-7e54-11ea-9c97-0268fe50e504.png)

**Comment by Unm1821** [comment]
Home page > area loghi >
Aggiungere logo CSVAA in una nuova categoria PARTNER (da mettere in ordine per 2° tra Istituzionali e media)

**Comment by dicarl** [comment]
inserita nuova categoria partner e logo csvaa
