### ISSUE TITLE
Priorità 2 - Inserimento campo Potrebbe interessarti anche questo

### ISSUE THREAD

**Issue by Unm1821** [lab121/covid19alessandria.help#30]
PAGINE  CATEGORIE:

Iniziative solidali >> "Potrebbe interessarti anche questo" >> Titolo e Link a pagina https://covid19alessandria.help/scopri/assistenza-alla-persona/

Mangiare e fare la spesa >> "Potrebbe interessarti anche questo" >> Titolo e Link a pagina https://covid19alessandria.help/scopri/educazione-e-cultura/iniziative-locali/

Assistenza alla persona >> "Potrebbe interessarti anche questo" >> Titolo e Link a pagina https://covid19alessandria.help/scopri/misure-di-sostegno-economico/

Misure di sostegno economico >> "Potrebbe interessarti anche questo" >> Titolo e Link a pagina https://covid19alessandria.help/scopri/assistenza-alla-persona/

Educazione e cultura >> "Potrebbe interessarti anche questo" >> Titolo e Link a pagina https://covid19alessandria.help/scopri/mangiare-e-fare-la-spesa/

Spostamenti >> "Potrebbe interessarti anche questo" >> Titolo e Link a pagina https://covid19alessandria.help/scopri/informazioni-utili/

Informazioni utili >> "Potrebbe interessarti anche questo" >> Titolo e Link a pagina
https://covid19alessandria.help/le-parole-del-covid/

PAGINE:

Emergenze  >> "Potrebbe interessarti anche questo" >> Titolo e Link a pagina https://covid19alessandria.help/scopri/iniziative-solidali/ - 

Le parole del Covid >> "Potrebbe interessarti anche questo" >> Titolo e Link a pagina https://covid19alessandria.help/buone-pratiche/

Buone pratiche >> "Potrebbe interessarti anche questo" >> Titolo e Link a pagina https://covid19alessandria.help/scopri/educazione-e-cultura/iniziative-locali/

**Comment by lussoluca** [comment]
Fatto, ho aggiunto un nuovo parametro nell'intestazione delle sezioni per indicare le pagine correlate (potrebbero essere anche più di una)

`
relate: ["/scopri/iniziative-solidali"]
`
