### ISSUE TITLE
Priorità 1 - è possibile inserire forum?

### ISSUE THREAD

**Issue by Unm1821** [lab121/covid19alessandria.help#32]
Vorremmo offrire un luogo di conversazione (diviso in argomenti) tipo forum.
cosa possiamo fare perché sia accessibile sulla piattaforma e non richieda iscrizioni a github o altro?

**Comment by lussoluca** [comment]
Il forum è stato installato sul''account AWS del Lab ed è disponibile qua: http://forum.covid19alessandria.help/
