### ISSUE TITLE
Priorità 1 - Modifiche menù e loghi grandi in home page

### ISSUE THREAD

**Issue by Unm1821** [lab121/covid19alessandria.help#37]
la pagina "Buone pratiche" va sotto "Scopri" > scompare dai loghi grandi in home page e cambia nel menù a tendina

Nuova pagina: "DPI" ( di fatto, al posto di Buone pratiche) > tra i loghi grandi in home page e nel menù a tendina

**Comment by Unm1821** [comment]
la pagina DPI sarà divisa in 2 sezioni:

la prima conterrà "Informazioni" da fonti ufficiali su come autoprodurre mascherine ecc o come usare prodotti e DPI (possiamo inserire anche dei video esterni?)

la secondo pagina "Trova DPI" conterrà poi le notizie di esercizi, organizzazioni ed Enti che producono o distribuiscono DPI

(i contenuti li stiamo raccogliendo)

**Comment by lussoluca** [comment]
@Unm1821 possiamo inserire anche dei video esterni? si, Hugo supporta di default Yutube e Vimeo

**Comment by lussoluca** [comment]
Direi che questo è stato tutto fatto da @dicarl
