### ISSUE TITLE
Aggiungere la sezione "buone pratiche"

### ISSUE THREAD

**Issue by lussoluca** [lab121/covid19alessandria.help#5]

**Comment by Unm1821** [comment]
Il logo che ha fatto Za per le buone pratiche va prima di emergenze (4° posizione), così lasciamo le più importanti all'inizio e alla fine.
La pagina Buone pratiche dovrebbe apparire con titolo, descrizione e direttamente l'elenco dei contenuti riquadrati.

**Comment by lussoluca** [comment]
@Unm1821 sezione creata: https://covid19alessandria.help/buone-pratiche/

Ho messo un post di prova
