### ISSUE TITLE
"chi siamo" da verificare nella versione desktop

### ISSUE THREAD

**Issue by AlessioCeS** [lab121/covid19alessandria.help#6]
Nella versione mobile il "chi siamo" funziona con i loghi e sulla desktop no

**Comment by lussoluca** [comment]
Non capisco cosa intendi con "non funziona"...

**Comment by AlessioCeS** [comment]
Che prima non vedevo i loghi sotto il testo 
Ora si.

**Comment by lussoluca** [comment]
perfetto
