### ISSUE TITLE
Logo Fondazione CRAL

### ISSUE THREAD

**Issue by Unm1821** [lab121/covid19alessandria.help#61]
Aggiungere nel footer logo Fondazione CRAL
sotto i partner
con la dicitura 
"con il contributo di"
![CRAL_Fondazione_piccolo-696x368](https://user-images.githubusercontent.com/62957867/102011405-11c31480-3d44-11eb-9fb6-dacd069f6081.gif)

**Comment by lussoluca** [comment]
fatto
